name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crystal-lang/install-crystal@v1
      - name: Install dependencies
        run: shards install
      - name: Build
        run: crystal build --no-codegen src/pnggif.cr src/encode.cr
